apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "custom.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.virtualservice.ingressGateway }}
  hosts:
    - {{ .Values.virtualservice.hosts }}
  http:
    - match:
        - uri:
            prefix: /{{ .Values.virtualservice.prefix }}
      route:
        - destination:
            host: {{ $.Release.Name }}.{{ $.Release.Namespace }}.svc.cluster.local
            port:
              number: 8080